#!/usr/bin/env python3
"""Build a compact Alimama display-font subset for text used by the wiki."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fontTools import subset


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WIKI_ROOT = PROJECT_ROOT / "wiki"
SOURCE_FONT = WIKI_ROOT / "public" / "fonts" / "AlimamaDongFangDaKai-Regular.woff2"
TARGET_DIR = WIKI_ROOT / "public" / "fonts" / "alimama-dakai-subset"
TARGET_CSS = WIKI_ROOT / "src" / "styles" / "display-font.generated.css"
LEGACY_TARGET = WIKI_ROOT / "public" / "fonts" / "AlimamaDongFangDaKai-Wiki.woff2"
TEXT_SOURCE_SUFFIXES = {".astro", ".ts"}
DISPLAY_DATA_KEYS = {"name", "title", "shortName"}


def collect_display_values(value: Any, characters: set[str], key: str = "") -> None:
    if isinstance(value, dict):
        for child_key, child_value in value.items():
            collect_display_values(child_value, characters, child_key)
        return
    if isinstance(value, list):
        for child in value:
            collect_display_values(child, characters, key)
        return
    if isinstance(value, str) and key in DISPLAY_DATA_KEYS:
        characters.update(value)


def display_characters() -> str:
    characters = set(" 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz·—-+%（）()《》：:，,。！？!?/与")
    source_root = WIKI_ROOT / "src"

    for path in source_root.rglob("*"):
        if not path.is_file() or path.suffix not in TEXT_SOURCE_SUFFIXES:
            continue
        characters.update(path.read_text(encoding="utf-8"))

    for path in (source_root / "data").glob("*.json"):
        with path.open(encoding="utf-8") as stream:
            collect_display_values(json.load(stream), characters)

    return "".join(sorted(character for character in characters if not character.isspace()))


def subset_options() -> subset.Options:
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
    options.name_legacy = True
    options.name_languages = [0x409, 0x804]
    return options


def main() -> None:
    if not SOURCE_FONT.exists():
        raise FileNotFoundError(f"Missing source font: {SOURCE_FONT}")

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    if LEGACY_TARGET.exists():
        LEGACY_TARGET.unlink()
    for stale_font in TARGET_DIR.glob("*.woff2"):
        stale_font.unlink()

    characters = display_characters()
    blocks: dict[int, list[str]] = {}
    for character in characters:
        blocks.setdefault(ord(character) >> 8, []).append(character)

    css_blocks = ["/* Generated by scripts/subset_display_font.py. */"]
    target_size = 0
    for block, block_characters in sorted(blocks.items()):
        options = subset_options()
        font = subset.load_font(str(SOURCE_FONT), options)
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(text="".join(block_characters))
        subsetter.subset(font)

        filename = f"u{block:04x}.woff2"
        target = TARGET_DIR / filename
        subset.save_font(font, str(target), options)
        target_size += target.stat().st_size

        range_start = block << 8
        range_end = range_start + 0xFF
        css_blocks.append(
            "\n".join(
                [
                    "@font-face {",
                    "  font-family: 'Alimama DongFang DaKai';",
                    f"  src: url('/fonts/alimama-dakai-subset/{filename}') format('woff2');",
                    "  font-style: normal;",
                    "  font-weight: 400;",
                    "  font-display: swap;",
                    f"  unicode-range: U+{range_start:04X}-{range_end:04X};",
                    "}",
                ]
            )
        )

    TARGET_CSS.write_text("\n\n".join(css_blocks) + "\n", encoding="utf-8")

    source_size = SOURCE_FONT.stat().st_size
    reduction = (1 - target_size / source_size) * 100
    print(
        f"Display font: {len(characters)} characters in {len(blocks)} chunks, "
        f"{source_size:,} -> {target_size:,} bytes total ({reduction:.1f}% smaller)."
    )


if __name__ == "__main__":
    main()
